// <auto-generated> Generated from Quill/Shaders/Canvas.slang by Quill.ShaderGen. Do not edit.
//
// Matrix convention: Slang emits mul(M, v) as v * M, so every mat4 uniform here must be
// uploaded transposed (glUniformMatrix4fv with transpose = true) relative to the matrix the
// canvas hands the backend. Same bytes as before, flipped flag.

namespace Engine.Platform.OpenGL.Paper;

internal static class CanvasShaders
{
    public const string Vertex = @"#version 330
uniform mat4 projection;

out vec2 vary_fragTexCoord;

out vec4 vary_fragColor;

out vec2 vary_fragPos;

layout(location = 0)
in vec2 input_aPosition_0;

layout(location = 1)
in vec2 input_aTexCoord_0;

layout(location = 2)
in vec4 input_aColor_0;

struct VertexOutput_0
{
    vec4 position_0;
    vec2 fragTexCoord_0;
    vec4 fragColor_0;
    vec2 fragPos_0;
};

void main()
{
    VertexOutput_0 output_0;
    output_0.fragTexCoord_0 = input_aTexCoord_0;
    output_0.fragColor_0 = input_aColor_0;
    output_0.fragPos_0 = input_aPosition_0;
    output_0.position_0 = (((vec4(input_aPosition_0, 0.0, 1.0)) * (projection)));
    VertexOutput_0 _S1 = output_0;

    gl_Position = output_0.position_0;

    vary_fragTexCoord = _S1.fragTexCoord_0;

    vary_fragColor = _S1.fragColor_0;

    vary_fragPos = _S1.fragPos_0;

    return;
}

";

    public const string Fragment = @"#version 330
uniform sampler2D fontTexture;

uniform sampler2D texture0;

uniform sampler2D backdropTexture;

uniform vec4 scissorTransform;
uniform vec2 scissorTranslation;
uniform vec2 scissorExt;
uniform vec4 brushTransform;
uniform vec2 brushTranslation;
uniform int brushType;
uniform vec4 brushColor1;
uniform vec4 brushColor2;
uniform vec4 brushParams;
uniform vec2 brushParams2;
uniform vec4 textureTransform;
uniform vec2 textureTranslation;
uniform vec2 atlasTexelSize;
uniform float sdfPxRange;
uniform vec2 viewportSize;
uniform float backdropBlurAmount;
uniform int backdropFlipY;

vec2 applyTransform_0(vec4 transform_0, vec2 translation_0, vec2 p_0)
{
    return vec2(dot(transform_0.xy, p_0), dot(transform_0.zw, p_0)) + translation_0;
}

float scissorMask_0(vec2 p_1)
{

    bool _S1;

    if((scissorExt.x) < 0.0)
    {

        _S1 = true;

    }
    else
    {

        _S1 = (scissorExt.y) < 0.0;

    }

    if(_S1)
    {

        return 1.0;
    }

    vec2 smoothEdges_0 = scissorExt - abs(applyTransform_0(scissorTransform, scissorTranslation, p_1));

    return clamp(smoothEdges_0.x, 0.0, 1.0) * clamp(smoothEdges_0.y, 0.0, 1.0);
}

float calculateBrushFactor_0(vec2 fragPos_0)
{
    vec2 transformedPoint_0 = applyTransform_0(brushTransform, brushTranslation, fragPos_0);

    if((brushType) == 1)
    {
        vec2 startPoint_0 = brushParams.xy;

        vec2 line_0 = brushParams.zw - startPoint_0;
        float lineLength_0 = length(line_0);
        if(lineLength_0 < 0.00100000004749745)
        {

            return 0.0;
        }

        return clamp(dot(transformedPoint_0 - startPoint_0, line_0) / (lineLength_0 * lineLength_0), 0.0, 1.0);
    }
    if((brushType) == 2)
    {

        return clamp(smoothstep(brushParams.z, brushParams.w, length(transformedPoint_0 - brushParams.xy)), 0.0, 1.0);
    }
    if((brushType) == 3)
    {
        vec2 center_0 = brushParams.xy;
        vec2 halfSize_0 = brushParams.zw;
        float radius_0 = brushParams2.x;
        float feather_0 = brushParams2.y;

        bool _S2;
        if((halfSize_0.x) < 0.00100000004749745)
        {

            _S2 = true;

        }
        else
        {

            _S2 = (halfSize_0.y) < 0.00100000004749745;

        }

        if(_S2)
        {

            return 0.0;
        }
        vec2 q_0 = abs(transformedPoint_0 - center_0) - (halfSize_0 - vec2(radius_0));

        return smoothstep(- feather_0 * 0.5, feather_0 * 0.5, min(max(q_0.x, q_0.y), 0.0) + length(max(q_0, vec2(0.0))) - radius_0);
    }
    return 0.0;
}

float sdfScreenPxRange_0(vec2 uv_0)
{

    return max(0.5 * dot(vec2(sdfPxRange) * atlasTexelSize, vec2(1.0) / (fwidth((uv_0)))), 1.0);
}

layout(location = 0)
out vec4 finalColor;

in vec2 vary_fragTexCoord;

in vec4 vary_fragColor;

in vec2 vary_fragPos;

void main()
{
    float mask_0 = scissorMask_0(vary_fragPos);

    vec4 color_0;

    if((brushType) > 0)
    {

        color_0 = mix(brushColor1, brushColor2, vec4(calculateBrushFactor_0(vary_fragPos)));

    }
    else
    {

        color_0 = vary_fragColor;

    }

    if((vary_fragTexCoord.x) >= 2.0)
    {
        vec2 uv_1 = vary_fragTexCoord - vec2(2.0);

        finalColor = color_0 * clamp(sdfScreenPxRange_0(uv_1) * ((texture((fontTexture), (uv_1))).x - 0.5) + 0.5, 0.0, 1.0) * mask_0;

        return;
    }

    float edgeAlpha_0 = clamp(vary_fragTexCoord.x, 0.0, 1.0);

    vec4 fill_0 = color_0 * (texture((texture0), (applyTransform_0(textureTransform, textureTranslation, vary_fragPos))));

    if((backdropBlurAmount) > 0.0)
    {
        vec2 uv_2 = vary_fragPos / viewportSize;
        if((backdropFlipY) == 1)
        {

            uv_2[1] = 1.0 - uv_2.y;

        }

        finalColor = vec4((texture((backdropTexture), (uv_2))).xyz * (1.0 - fill_0.w) + fill_0.xyz, 1.0) * edgeAlpha_0 * mask_0;

        return;
    }

    finalColor = fill_0 * edgeAlpha_0 * mask_0;

    return;
}

";

}
