<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\build\GameScriptReferences.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="ECS">
            <HintPath>$(GameScriptSdkPath)ECS.dll</HintPath>
        </Reference>
        <Reference Include="Input">
            <HintPath>$(GameScriptSdkPath)Input.dll</HintPath>
        </Reference>
        <Reference Include="SceneComponents">
            <HintPath>$(GameScriptSdkPath)SceneComponents.dll</HintPath>
        </Reference>
        <Reference Include="Scripting">
            <HintPath>$(GameScriptSdkPath)Scripting.dll</HintPath>
        </Reference>
        <Reference Include="Math">
            <HintPath>$(GameScriptSdkPath)Math.dll</HintPath>
        </Reference>
        <Reference Include="Box2D.NetStandard">
            <HintPath>$(GameScriptSdkPath)Box2D.NetStandard.dll</HintPath>
        </Reference>
    </ItemGroup>


</Project>
