<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Audio\Audio.csproj" />
        <ProjectReference Include="..\..\ECS\ECS.csproj" />
        <ProjectReference Include="..\..\Input\Input.csproj" />
        <ProjectReference Include="..\..\Math\Math.csproj" />
        <ProjectReference Include="..\..\SceneComponents\SceneComponents.csproj" />
        <ProjectReference Include="..\..\Scripting\Scripting.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="assets\" />
    </ItemGroup>
</Project>
