name: Claude Editor Agent

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/editor')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/editor')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '/editor')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@/editor') || contains(github.event.issue.title, '/editor')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # Add reaction emoji immediately when triggered
      - name: Add reaction to comment
        if: github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment'
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content=eyes
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Optional: Give a custom prompt to Claude. If this is not specified, Claude will perform the instructions specified in the comment that tagged it.
          prompt: |
            REPO: ${{ github.repository }}
            ISSUE NUMBER: ${{ github.event.issue.number }}
            Use the game-editor-architect agent. Be concise.
            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.
            Use `gh issue comment` with your Bash tool to leave your review as a comment on the issue.
          trigger_phrase: "/editor"
        env:
          GH_TOKEN: ${{ github.token }}

